<?php

namespace App\Services\Crm;

use App\Models\Architect;
use App\Models\CrmOpportunity;

class ArchitectService
{
    /**
     * Calculate total accumulated Commission (RT) for an architect.
     */
    public function calculateTotalCommission(Architect $architect): float
    {
        // We sum the calculated commission for all WON opportunities linked to this architect
        
        $total = 0;
        $wonOpportunities = $architect->opportunities()->where('stage_id', 'won')->get();

        foreach ($wonOpportunities as $opportunity) {
            // Priority: Opportunity specific RT percent > Architect Default %
            // Ideally should use value stored at deal closing.
            // Using current architect default for now.
            
            $percentage = $architect->rt_percentage ?? 0; 
            $value = $opportunity->estimated_value;
            
            $total += ($value * ($percentage / 100));
        }

        return $total;
    }

    /**
     * Calculate total Sales Volume generated by the architect.
     */
    public function calculateTotalSales(Architect $architect): float
    {
        return $architect->opportunities()->where('stage_id', 'won')->sum('estimated_value');
    }
}
